apiVersion: v1
kind: Namespace
metadata:
  name: default
  # the following annotation will be needed when using argoCD with Operator
  labels:
    argocd.argoproj.io/managed-by: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-app 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: '.'
    repoURL: https://github.com/k8strainer/external-secrets-operator.git
    targetRevision: main
  syncPolicy:
    automated:
      # prune resources in live cluster if not available any more in Git
      prune: true
      # By default, changes that are made to the live cluster will not trigger automated sync. 
      # To enable automatic sync when the live cluster's state deviates from the state defined in Git, run: 
      selfHeal: true
    # sync retry  
    retry:
      limit: 5
    #syncOptions:
    #- PrunePropagationPolicy=foreground
    #- Replace=false
    #- PruneLast=false
    #- Validate=true
    #- CreateNamespace=true
    #- ApplyOutOfSyncOnly=false
    #- ServerSideApply=true
    #- RespectIgnoreDifferences=false