apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-external-secret
spec:
  secretStoreRef:
    kind: SecretStore
    name: gcp-backend
  refreshInterval: 10s
  target:
    name: secret-created-from-eso-secret
  data: 
  - secretKey: password_file 
    remoteRef: 
      key: eso-secret
      version: "1"
      ## contains "password":"verysecret"
      #version: "2"
      ## contains "password":"evenmoresecret"
      #
      ## ACHTUNG: Es kann nach der Umstellung hier 3-4 Minuten dauern bis die Änderung propagiert ist
      ## (u.a. Polling Zyklus ESO, Secret-Refresh durch die kubelets, inotyfywait)

