apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-external-secret
spec:
  secretStoreRef:
    kind: SecretStore
    name: gcp-backend
  refreshInterval: 10s
  target:
    name: secret-created-from-eso-secret
  data: 
  - secretKey: password_file 
    remoteRef: 
      key: eso-secret
      #version: "1"
      ## contains "password":"verysecret"
      #version: "2"
      ## contains "password":"evenmoresecret"

